export default {
  $id: "page",
  additionalProperties: false,
  dynamicDefaults: { id: "uuid" },
  properties: {
    changefreq: {
      default: null,
      enum: [
        "always",
        "hourly",
        "daily",
        "weekly",
        "monthly",
        "yearly",
        "never",
        null,
      ],
      nullable: true,
      type: "string",
    },
    children: {
      default: [],
      items: { type: "object" },
      type: "array",
    },
    class: {
      default: ["prose", "max-w-none"],
      items: { type: "string" },
      type: "array",
    },
    description: { default: null, nullable: true, type: "string" },
    enabled: { default: true, type: "boolean" },
    flat: { default: true, type: "boolean" },
    frontmatter: {
      default: null,
      nullable: true,
      properties: { head: { type: "object" } },
      type: "object",
    },
    header: { type: "string" },
    icon: { type: "string" },
    id: { type: "string" },
    images: {
      default: [],
      items: {
        additionalProperties: false,
        properties: {
          alt: { type: "string" },
          url: { default: "", type: "string" },
        },
        type: "object",
      },
      type: "array",
    },
    keywords: {
      default: [],
      items: { type: "string" },
      type: "array",
    },
    lastmod: { default: null, nullable: true, type: "string" },
    loc: { default: null, nullable: true, type: "string" },
    name: { default: null, nullable: true, type: "string" },
    priority: {
      default: null,
      maximum: 1,
      minimum: 0,
      nullable: true,
      type: "number",
    },
    type: {
      default: null,
      enum: [
        "article",
        "book",
        "profile",
        "website",
        "music.song",
        "music.album",
        "music.playlist",
        "music.radio_station",
        "video.movie",
        "video.episode",
        "video.tv_show",
        "video.other",
        null,
      ],
      nullable: true,
      type: "string",
    },
  },
  type: "object",
} as const;
